version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    hostname: app
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    networks:
      - backend
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'tasky'