FROM postgres:12

# Configura las variables de entorno para PostgreSQL
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expone el puerto por defecto de PostgreSQL (5432)
EXPOSE 5432