FROM postgres:12

# Configura las variables de entorno para PostgreSQL
ENV POSTGRES_DB=tasky
ENV POSTGRES_USER=tasky
ENV POSTGRES_PASSWORD=tasky

# Expone el puerto por defecto de PostgreSQL (5432)
EXPOSE 5432